export const PREFIX = "@todos/";

export const GET_ALL_TODOS = `${PREFIX}GET_ALL_TODOS`;
export const GET_ALL_TODOS_SUCCESS = `${PREFIX}GET_ALL_TODOS_SUCCESS`;
export const GET_ALL_TODOS_FAILED = `${PREFIX}GET_ALL_TODOS_FAILED`;

export const ADD_TODO = `${PREFIX}ADD_TODO`;
export const ADD_TODO_SUCCESS = `${PREFIX}ADD_TODO_SUCCESS`;
export const ADD_TODO_FAILED = `${PREFIX}ADD_TODO_FAILED`;

export const UPDATE_TODO_STATE = `${PREFIX}UPDATE_TODO_STATE`;
export const UPDATE_TODO_STATE_SUCCESS = `${PREFIX}UPDATE_TODO_STATE_SUCCESS`;
export const UPDATE_TODO_STATE_FAILED = `${PREFIX}UPDATE_TODO_STATE_FAILED`;

export const UPDATE_ALL_TODOS_STATE = `${PREFIX}UPDATE_ALL_TODOS_STATE`;
export const UPDATE_ALL_TODOS_STATE_SUCCESS = `${PREFIX}UPDATE_ALL_TODOS_STATE_SUCCESS`;
export const UPDATE_ALL_TODOS_STATE_FAILED = `${PREFIX}UPDATE_ALL_TODOS_STATE_FAILED`;

export const DELETE_TODO = `${PREFIX}DELETE_TODO`;
export const DELETE_TODO_SUCCESS = `${PREFIX}DELETE_TODO_SUCCESS`;
export const DELETE_TODO_FAILED = `${PREFIX}DELETE_TODO_FAILED`;

export const DELETE_COMPLETED_TODOS = `${PREFIX}DELETE_COMPLETED_TODOS`;
export const DELETE_COMPLETED_TODOS_SUCCESS = `${PREFIX}DELETE_COMPLETED_TODOS_SUCCESS`;
export const DELETE_COMPLETED_TODOS_FAILED = `${PREFIX}DELETE_COMPLETED_TODOS_FAILED`;

export const SET_TODO_INPUT_VALUE = `${PREFIX}SET_TODO_INPUT_VALUE`;

export const SET_TODO_FILTER = `${PREFIX}SET_TODO_FILTER`;
